### PR TITLE
updated to work with Django3.2

### LINKED ISSUE #16: crash on django 3.2 due to `_headers` deprecation
```
File "/python3.9/site-packages/server_timing/middleware.py", line 71, in process_response
    response._headers['server-timing'] = ('Server-Timing', ','.join(services))
AttributeError: 'HttpResponse' object has no attribute '_headers'
```
This is due to the deprecation of `_headers` in [Django 3.2](https://docs.djangoproject.com/en/3.2/releases/3.2/#requests-and-responses)

### PR DESCRIPTION
**Pull request by matthewhegarty**
Fixes #16 

- Middleware now updates `headers` not '_headers`
- Fixed `make test`
- Updated dependencies
- Added test
- Added required `SECRET_KEY` to conf test
- Fixed deprecation warning in urls.py

#### Testing

- Unit tests pass
- Tested with the example app

### CODE REVIEW

**Comment by vtemian** [comment]
Thanks, @matthewhegarty for your contribution!
